import type { ElectricalInstallation } from "@bali-moto-track/shared-types";

// Datos demo del "pasaporte eléctrico digital" de Luna Beach Club. Documenta la
// instalación de la acometida PLN al comisionado, con fotos, datos técnicos y la
// relación llave→circuito→tablero. Ver la sección Electrical en docs/buildtrack-prd.md.
// (Fotos = frames de obra reutilizados como placeholder hasta tener las reales.)

export const LUNA_ELECTRICAL: ElectricalInstallation = {
  overallPct: 72,
  phases: [
    {
      id: "e-p1",
      number: 1,
      name: "Infraestructura principal",
      status: "completed",
      progressPct: 100,
      description: "Acometida PLN, tablero general, térmicas principales, puesta a tierra y protección contra sobretensiones.",
    },
    {
      id: "e-p2",
      number: 2,
      name: "Cañerías y cableado",
      status: "completed",
      progressPct: 100,
      description: "Registro fotográfico de caños y tendido antes de cerrar paredes y cielorrasos.",
    },
    {
      id: "e-p3",
      number: 3,
      name: "Llaves y tomas",
      status: "in_progress",
      progressPct: 65,
      description: "Cada llave y toma con circuito, térmica y destino marcados en el plano digital.",
    },
    {
      id: "e-p4",
      number: 4,
      name: "Sistema de iluminación",
      status: "in_progress",
      progressPct: 40,
      description: "Luminarias, tiras LED, iluminación de jardín, de pileta y de emergencia.",
    },
    {
      id: "e-p5",
      number: 5,
      name: "Conexión de equipos",
      status: "pending",
      progressPct: 10,
      description: "Aires, bombas, sistema de pileta, termotanques, cargadores EV, cocina y seguridad.",
    },
    {
      id: "e-p6",
      number: 6,
      name: "Testing y comisionado",
      status: "pending",
      progressPct: 0,
      description: "Ensayos de tensión, tierra, térmicas, carga e inspección final.",
    },
  ],
  components: [
    // --- Fase 1: infraestructura ---
    {
      id: "PLN-01",
      category: "panel",
      name: "Acometida PLN",
      room: "Sala de medidores",
      photo: "/images/prod-medidor.jpg",
      installedAt: "2026-04-08",
      installer: "PT Listrik Bali",
      specs: "Trifásica 380V · 23 kVA · medidor prepago",
    },
    {
      id: "DB-01",
      category: "panel",
      name: "Tablero general DB-01",
      room: "Sala eléctrica",
      photo: "/images/electrical-panel.jpg",
      installedAt: "2026-04-15",
      installer: "Ketut Wira · CV Arus Bali",
      specs: "18 circuitos · barra 63A · IP54 · con SPD tipo 2",
    },
    {
      id: "DB-02",
      category: "panel",
      name: "Tablero seccional DB-02 (pileta/jardín)",
      room: "Sector oeste",
      photo: "/images/elec-board2.jpg",
      installedAt: "2026-05-02",
      installer: "Ketut Wira · CV Arus Bali",
      specs: "8 circuitos · 40A · diferencial 30mA",
    },
    {
      id: "GND-01",
      category: "panel",
      name: "Puesta a tierra",
      room: "Perímetro",
      photo: "/images/elec-ground.jpg",
      installedAt: "2026-04-12",
      installer: "CV Arus Bali",
      specs: "3 jabalinas · malla de cobre · 0.8 Ω medidos",
    },
    // --- Fase 3: llaves y tomas (el ejemplo del PRD) ---
    {
      id: "S-01",
      category: "switch",
      name: "Llave S-01",
      room: "Living principal",
      photo: "/images/prod-enchufe1.jpg",
      installedAt: "2026-06-18",
      installer: "Made Sudana",
      circuit: "C-03",
      panel: "DB-01",
      breaker: "10A",
      controls: "Luces principales del living",
    },
    {
      id: "S-02",
      category: "switch",
      name: "Llave S-02",
      room: "Terraza oeste",
      photo: "/images/prod-enchufe1.jpg",
      installedAt: "2026-06-20",
      installer: "Made Sudana",
      circuit: "C-07",
      panel: "DB-02",
      breaker: "10A",
      controls: "Iluminación de terraza y borde de pileta",
    },
    {
      id: "O-05",
      category: "outlet",
      name: "Toma O-05 (doble)",
      room: "Cocina",
      photo: "/images/prod-enchufe2.jpg",
      installedAt: "2026-06-22",
      installer: "Made Sudana",
      circuit: "C-11",
      panel: "DB-01",
      breaker: "16A",
      controls: "Mesada de cocina",
    },
    // --- Cajas eléctricas (paso / derivación) ---
    {
      id: "JB-01",
      category: "box",
      name: "Caja de paso principal",
      room: "Pasillo técnico",
      photo: "/images/elec-box.jpg",
      installedAt: "2026-06-10",
      installer: "Ketut Wira · CV Arus Bali",
      circuit: "C-03",
      panel: "DB-01",
      specs: "Caja 200×200mm IP55 · derivación de living y cocina",
    },
    {
      id: "JB-02",
      category: "box",
      name: "Caja de derivación · pileta",
      room: "Sector oeste",
      photo: "/images/elec-box.jpg",
      installedAt: "2026-07-03",
      installer: "Ketut Wira · CV Arus Bali",
      circuit: "C-14",
      panel: "DB-02",
      specs: "Caja estanca IP68 · alimenta luces de pileta y bomba",
    },
    // --- Fase 4: iluminación ---
    {
      id: "L-POOL",
      category: "lighting",
      name: "Luces de pileta RGB",
      room: "Pileta oeste",
      photo: "/images/elec-poollight.jpg",
      installedAt: "2026-07-05",
      installer: "CV Arus Bali",
      circuit: "C-14",
      panel: "DB-02",
      breaker: "6A",
      specs: "6 focos LED 24V IP68 · control DMX",
    },
    {
      id: "L-GARDEN",
      category: "lighting",
      name: "Iluminación de jardín",
      room: "Jardín perimetral",
      photo: "/images/elec-gardenlight.jpg",
      installedAt: "2026-07-08",
      installer: "CV Arus Bali",
      circuit: "C-15",
      panel: "DB-02",
      breaker: "6A",
      specs: "14 balizas LED 12V · fotocélula",
    },
    // --- Fase 5: equipos ---
    {
      id: "EQ-POOL",
      category: "equipment",
      name: "Bomba y filtro de pileta",
      room: "Sala de máquinas",
      photo: "/images/elec-pump.jpg",
      installedAt: "2026-07-10",
      installer: "Pending commissioning",
      circuit: "C-18",
      panel: "DB-02",
      breaker: "20A",
      load: "2.2 kW",
      specs: "Bomba 3HP + sistema de filtrado",
    },
    {
      id: "EQ-AC1",
      category: "equipment",
      name: "Aire acondicionado · Suite 1",
      room: "Suite principal",
      photo: "/images/elec-ac.jpg",
      circuit: "C-09",
      panel: "DB-01",
      breaker: "16A",
      load: "1.8 kW",
      specs: "Split inverter 12.000 BTU",
    },
    {
      id: "EQ-UPS",
      category: "equipment",
      name: "Sistema de respaldo (inversor)",
      room: "Sala eléctrica",
      photo: "/images/prod-bateria.jpg",
      installedAt: "2026-07-12",
      installer: "CV Arus Bali",
      circuit: "C-20",
      panel: "DB-01",
      breaker: "25A",
      load: "3.0 kW",
      specs: "Inversor/cargador 3kVA + banco de baterías 48V (respaldo de cortes PLN)",
    },
  ],
  tests: [
    { id: "t-gnd", name: "Puesta a tierra", result: "pass", value: "0.8 Ω", date: "2026-04-13" },
    { id: "t-volt", name: "Tensión de línea (trifásica)", result: "pass", value: "228/395 V", date: "2026-06-25" },
    { id: "t-break", name: "Disparo de térmicas y diferenciales", result: "pass", value: "30mA / 25ms", date: "2026-06-26" },
    { id: "t-load", name: "Prueba de carga (parcial)", result: "pending", date: "—" },
    { id: "t-final", name: "Inspección final y comisionado", result: "pending", date: "—" },
  ],
};

// Hotel Cliff Pantay Nany — obra en etapa media (techo). Instalación eléctrica
// arrancada: infraestructura lista, cañerías y cajas en curso, sin equipos aún.
export const CLIFF_ELECTRICAL: ElectricalInstallation = {
  overallPct: 34,
  phases: [
    { id: "e-p1", number: 1, name: "Infraestructura principal", status: "completed", progressPct: 100, description: "Acometida PLN, tablero general y puesta a tierra." },
    { id: "e-p2", number: 2, name: "Cañerías y cableado", status: "in_progress", progressPct: 55, description: "Tendido de caños antes de cerrar losas." },
    { id: "e-p3", number: 3, name: "Llaves y tomas", status: "pending", progressPct: 5, description: "A la espera de cerrar paredes." },
    { id: "e-p4", number: 4, name: "Sistema de iluminación", status: "pending", progressPct: 0, description: "No iniciado." },
    { id: "e-p5", number: 5, name: "Conexión de equipos", status: "pending", progressPct: 0, description: "No iniciado." },
    { id: "e-p6", number: 6, name: "Testing y comisionado", status: "pending", progressPct: 0, description: "No iniciado." },
  ],
  components: [
    { id: "PLN-01", category: "panel", name: "Acometida PLN", room: "Sala de medidores", photo: "/images/prod-medidor.jpg", installedAt: "2026-05-20", installer: "PT Listrik Bali", specs: "Trifásica 380V · 33 kVA" },
    { id: "DB-01", category: "panel", name: "Tablero general DB-01", room: "Sala eléctrica", photo: "/images/electrical-panel.jpg", installedAt: "2026-05-28", installer: "PT Cahaya Listrik", specs: "24 circuitos · barra 80A · IP54" },
    { id: "GND-01", category: "panel", name: "Puesta a tierra", room: "Perímetro", photo: "/images/elec-ground.jpg", installedAt: "2026-05-22", installer: "PT Cahaya Listrik", specs: "4 jabalinas · 0.9 Ω medidos" },
    { id: "JB-01", category: "box", name: "Caja de paso · planta baja", room: "Núcleo técnico", photo: "/images/elec-box.jpg", installedAt: "2026-06-15", installer: "PT Cahaya Listrik", panel: "DB-01", specs: "Caja 250×250mm IP55" },
  ],
  tests: [
    { id: "t-gnd", name: "Puesta a tierra", result: "pass", value: "0.9 Ω", date: "2026-05-23" },
    { id: "t-volt", name: "Tensión de línea", result: "pending", date: "—" },
  ],
};

// Villa Canggu Garden — obra DEMORADA en fundaciones. Eléctrica apenas iniciada:
// solo acometida provisoria de obra y proyecto en planos.
export const CANGGU_ELECTRICAL: ElectricalInstallation = {
  overallPct: 8,
  phases: [
    { id: "e-p1", number: 1, name: "Infraestructura principal", status: "in_progress", progressPct: 25, description: "Acometida provisoria de obra instalada; tablero definitivo pendiente." },
    { id: "e-p2", number: 2, name: "Cañerías y cableado", status: "pending", progressPct: 0, description: "A la espera de fundaciones." },
    { id: "e-p3", number: 3, name: "Llaves y tomas", status: "pending", progressPct: 0, description: "No iniciado." },
    { id: "e-p4", number: 4, name: "Sistema de iluminación", status: "pending", progressPct: 0, description: "No iniciado." },
    { id: "e-p5", number: 5, name: "Conexión de equipos", status: "pending", progressPct: 0, description: "No iniciado." },
    { id: "e-p6", number: 6, name: "Testing y comisionado", status: "pending", progressPct: 0, description: "No iniciado." },
  ],
  components: [
    { id: "TP-01", category: "panel", name: "Tablero provisorio de obra", room: "Ingreso de obra", photo: "/images/electrical-panel.jpg", installedAt: "2026-06-05", installer: "CV Arus Bali", specs: "Tablero de obra 4 circuitos · diferencial 30mA" },
  ],
  tests: [],
};
